# Main docker compose file

services:
  debian-13:
    image: "mrjk78/docker-homebox:debian-13-${app_image_version:-latest}"
    build:
      context: ./build/
      dockerfile: ./Dockerfile.debian
      target: homebox
      tags:
        - "mrjk78/docker-homebox:debian-13-${app_image_version:-latest}"
      args:
        BASE_IMAGE: debian:13-slim
        VERSION: ${app_image_version:-latest}
        GIT_COMMIT: ${app_image_commit:-0000000}
        BUILD_DATE: "${app_image_build_date:-1970-01-01T00:00:00Z}"
