# https://taskfile.dev

version: '3'

env:
  APP_USERNAME:
    sh: "docker compose config --environment | sed -n 's/app_username=//p'"

tasks:
  default:
    desc: List all commands
    cmds:
      - task --list-all
    silent: true

  # Build commands
  # =========================
  build:
    desc: Build images
    cmds:
      - docker compose --progress plain build

  run:
    desc: Run ephemeral container shell (via run)
    cmds:
      - docker compose run --rm -ti -u $APP_USERNAME user_debian /bin/bash

  run-root:
    desc: Run ephemeral container root shell (via run)
    cmds:
      - docker compose run --rm -ti -u root --entrypoint /bin/bash  user_debian

  upgrade:
    desc: Rebuild and recreate containers
    silent: true
    cmds:
      - task: build
      - task: down
      - docker compose up -d --build
      - 'echo "Waiting 3 seconds for logs ..."'
      - sleep 3
      - docker compose logs


  # Lifecycle commands
  # =========================

  env:
    cmds:
      - 'docker compose config --environment'

  config:
    desc: Show stack config
    cmds:
      - docker compose config

  down:
    desc: Down the stack
    cmds:
      - docker compose down

  up:
    desc: Up the stack
    cmds:
      - docker compose up -d

  recreate:
    desc: Redeploy stack
    aliases:
      - updown
      - apply
    cmds:
      - docker compose down
      - docker compose up -d

  update:
    desc: Rebuild and apply if necessary changes 
    silent: true
    cmds:
      - docker compose up -d --build
      - 'echo "Waiting 3 seconds for logs ..."'
      - sleep 3
      - docker compose logs


  # Runtime commands
  # =========================
  logs:
    desc: Show live logs
    cmds:
      - cmd: docker compose logs -f
        ignore_error: true

  enter:
    desc: Enter in current instance (via exec)
    cmds:
      - cmd: docker compose exec -ti -u $APP_USERNAME user_debian /bin/bash
        ignore_error: true
  enter-root:
    desc: Enter in current instance as root (via exec)
    cmds:
      - cmd: docker compose exec -ti -u root  user_debian /bin/bash
        ignore_error: true

