# https://taskfile.dev

version: '3'

env:

  # Docker configuration
  DOCKER_CONFIG: .tmp/docker-auth
  COMPOSE_PROGRESS: plain

  # Compose env vars
  app_image_build_date:
    sh: >
      date -u +"%Y-%m-%dT%H:%M:%SZ"
  app_image_version:
    sh: > 
      git symbolic-ref --short -q HEAD || git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD
  app_image_commit:
    sh: > 
      git rev-parse --short HEAD
  app_image_version:
    sh: semantic-release version --print-tag

vars:
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD

  VERSION_MINOR:
    sh: >
      echo "${app_image_version%.*}"

  VERSION_MAJOR:
    sh: >
      echo "${app_image_version%.*.*}"

  VERSION_DATE:
    sh: >
      date -u +"%Y-%m-%d"


includes:
  docs:
    taskfile: docs/Taskfile.yml
    dir: docs/

tasks:
  default:
    desc: List all commands
    cmds:
      - task --list-all
    silent: true

  # Local commands
  # =========================

  env:
    desc: Show compose environment vars
    cmds:
      - 'docker compose config --environment'

  config:
    desc: Show compose config
    cmds:
      - docker compose config

  build:
    desc: Build images
    cmds:
      - docker compose --progress plain build

  # CI/CD commands
  # =========================

  setup:
    desc: Setup ci/cd environment
    status:
      - command -v semantic-release
    cmds:
      - uv pip install -r requirements.txt

  release:
    desc: Make a new release
    aliases:
      - ci-release
    deps:
      - setup
    cmds:
      - semantic-release version
      - git push

  versions:
    desc: Show current and next version
    silent: true
    deps:
      - task: setup
        silent: true
    vars:
      current:
        sh: semantic-release version --print-last-released-tag
    cmds:
      - 'echo "Current version: {{.current}}"'
      - 'echo "Next version: $app_image_version"'


  # Remote - DockerHub
  # =========================

  login:
    desc: Login to registry
    silent: true
    if: "[ ! -f $DOCKER_CONFIG/config.json ]"
    cmds:
      - |
        mkdir -p "$DOCKER_CONFIG"
        echo "$DOCKERHUB_TOKEN" | docker login \
        --username "$DOCKERHUB_USERNAME" \
        --password-stdin

  logout:
    desc: Logout from registry
    cmds:
      - rm -f "$DOCKER_CONFIG/config.json"


  # Remote - Dev Releases
  # =========================

  push:
    desc: Push images on remote registry
    aliases:
      - ci-push
    deps:
      - build
      - login
    cmds:
      - docker tag "homebox:debian-13-${app_image_version}" "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-${app_image_version}"
      - docker push "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-${app_image_version}"


  # Remote - Stable Releases
  # =========================

  push-dockerhub-readme:
    desc: Push dockerhub readme
    preconditions:
      - sh: '[ "{{.BRANCH}}" = "main" ]'
        msg: "Must be on main branch (current: {{.BRANCH}})"
    cmds:
      - ./scripts/dockerhub-update-readme.sh

  push-latest:
    desc: Push current image tags to registry
    deps:
      - build
      - login
    preconditions:
      - sh: '[ "{{.BRANCH}}" = "main" ]'
        msg: "Must be on main branch (current: {{.BRANCH}})"
    cmds:
      - docker tag "homebox:debian-13-${app_image_version}" "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-${app_image_version}-{{.VERSION_DATE}}"
      - docker tag "homebox:debian-13-${app_image_version}" "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-{{.VERSION_MINOR}}"
      - docker tag "homebox:debian-13-${app_image_version}" "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-{{.VERSION_MAJOR}}"
      - docker tag "homebox:debian-13-${app_image_version}" "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-latest"
      - docker push "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-${app_image_version}-{{.VERSION_DATE}}"
      - docker push "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-{{.VERSION_MINOR}}"
      - docker push "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-{{.VERSION_MAJOR}}"
      - docker push "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-latest"

  push-stable:
    desc: release stable version
    aliases:
      - ci-release-stable
    preconditions:
      - sh: '[ "{{.BRANCH}}" = "main" ]'
        msg: "Must be on main branch (current: {{.BRANCH}})"
    cmds:
      - task: push
      - task: push-latest
      - task: push-dockerhub-readme
      - task: docs:publish
