# https://taskfile.dev

version: '3'

env:
  app_image_build_date:
    sh: >
      date -u +"%Y-%m-%dT%H:%M:%SZ"
  app_image_version:
    sh: > 
      git symbolic-ref --short -q HEAD || git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD
  app_image_commit:
    sh: > 
      git rev-parse --short HEAD

  DOCKER_CONFIG: .tmp/docker-auth

tasks:
  default:
    desc: List all commands
    cmds:
      - task --list-all
    silent: true

  # Build commands
  # =========================
  build:
    desc: Build images
    cmds:
      - docker compose --progress plain build

  push:
    desc: Push images
    deps:
      - login
    cmds:
      - docker compose push

  push-latest:
    desc: Push current image to latest
    deps:
      - login
    cmds:
      - docker tag "mrjk78/docker-homebox:debian-13-${app_image_version}" "mrjk78/docker-homebox:debian-13-latest"
      - docker push "mrjk78/docker-homebox:debian-13-latest"

  login:
    desc: Login to registry
    silent: true
    if: "[ ! -f $DOCKER_CONFIG/config.json ]"
    cmds:
      - |
        mkdir -p "$DOCKER_CONFIG"
        echo "$DOCKERHUB_TOKEN" | docker login \
        --username "$DOCKERHUB_USERNAME" \
        --password-stdin
  logout:
    desc: Logout from registry
    cmds:
      - rm -f "$DOCKER_CONFIG/config.json"


  # Info commands
  # =========================

  env:
    cmds:
      - 'docker compose config --environment'

  config:
    desc: Show stack config
    cmds:
      - docker compose config



  # CI/DC commands
  # =========================

  setup:
    desc: Setup ci/cd environment
    cmds:
      - uv pip install -r requirements.txt