# https://taskfile.dev

version: '3'

env:
  app_image_build_date:
    sh: >
      date -u +"%Y-%m-%dT%H:%M:%SZ"
  app_image_version:
    sh: > 
      git symbolic-ref --short -q HEAD || git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD
  app_image_commit:
    sh: > 
      git rev-parse --short HEAD

  DOCKER_CONFIG: .tmp/docker-auth

  #VERSION:
  #  sh: semantic-release version --print-last-released

  app_image_version:
    sh: semantic-release version --print-tag

vars:
  BRANCH:
    sh: git rev-parse --abbrev-ref HEAD


includes:
  docs:
    taskfile: docs/Taskfile.yml
    dir: docs/

tasks:
  default:
    desc: List all commands
    cmds:
      - task --list-all
    silent: true

  # Build commands
  # =========================
  build:
    desc: Build images
    cmds:
      - docker compose --progress plain build

  push:
    desc: Push images
    aliases:
      - ci-push
    deps:
      - build
      - login
    cmds:
      - docker compose push

  push-latest:
    desc: Push current image to latest
    aliases:
      - ci-push-latest
    deps:
      - build
      - login
    cmds:
      - docker tag "homebox:debian-13-${app_image_version}" "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-latest"
      - docker push "$DOCKERHUB_NAMESPACE/$DOCKERHUB_REPOSITORY:debian-13-latest"

  login:
    desc: Login to registry
    silent: true
    if: "[ ! -f $DOCKER_CONFIG/config.json ]"
    cmds:
      - |
        mkdir -p "$DOCKER_CONFIG"
        echo "$DOCKERHUB_TOKEN" | docker login \
        --username "$DOCKERHUB_USERNAME" \
        --password-stdin
  logout:
    desc: Logout from registry
    cmds:
      - rm -f "$DOCKER_CONFIG/config.json"


  # Info commands
  # =========================

  env:
    cmds:
      - 'docker compose config --environment'

  config:
    desc: Show stack config
    cmds:
      - docker compose config



  # CI/DC commands
  # =========================

  setup:
    desc: Setup ci/cd environment
    status:
      - command -v semantic-release
    cmds:
      - uv pip install -r requirements.txt

  release:
    desc: Make a new release
    aliases:
      - ci-release
    deps:
      - setup
    cmds:
      - semantic-release version
      - git push

  push-dockerhub-readme:
    desc: Push dockerhub readme
    aliases:
      - ci-push-readme
    cmds:
      - ./scripts/dockerhub-update-readme.sh

  push-stable:
    desc: release stable version
    preconditions:
      - sh: '[ "{{.BRANCH}}" = "main" ]'
        msg: "Must be on main branch (current: {{.BRANCH}})"
    cmds:
      - task: push
      - task: push-latest
      - task: push-dockerhub-readme
      - task: docs:publish
