---
# https://taskfile.dev
version: '3'

tasks:

  list:
    desc: "show available commands"
    aliases:
      - default
    silent: true
    cmds:
      - task --list-all

  # Zensical
  # =============

  setup:
    desc: Setup documentation environment
    status:
      - command -v zensical
    cmds:
      - uv pip install -r requirements.txt

  serve:
    desc: serve mkdoc website locally
    deps:
      - setup
    cmds:
      - zensical serve

  publish:
    desc: update gh_page branch with new documentation
    deps:
      - setup
    cmds:
      - zensical build
      - ./pages-deploy.sh

